#=====================================================================================
# Inversion parameters.
#=====================================================================================

   #==================================================================================
   # Method.
   #==================================================================================
   # HMC (Hamiltonian Monte Carlo), MH (Metropolis-Hastings), LIN (linear system).
   method = "HMC"

   #==================================================================================
   # Number of model parameters.
   #==================================================================================
   # 6 (moment tensor, M), 9 (M plus location), 10 (M plus location plus time).
   n = 10

   #==================================================================================
   # Tuning parameters.
   #==================================================================================
   # HMC gravitational constant (large: optimisation, small: exploration).
   hmc_gamma = 1.0
   # HMC mass matrix regularisation (small: little regularisation, large: mass matrix=identity).
   hmc_reg = 0.1

#=====================================================================================
# Source parameters.
#=====================================================================================

   #==================================================================================
   # Source location.
   #==================================================================================
   # Prior means of latitude [degree], longitude [degree], depth [km].
   lat = 141.0
   lon = 32.2
   depth = 51.0
   # Prior standard deviations of latitude [degree], longitude [degree], depth [km].
   sigma_lat = 2.0
   sigma_lon = 2.0
   sigma_depth = 4.0

   #==================================================================================
   # Moment tensor.
   #==================================================================================
   # Prior means of Mxx, Mxy, Mxz, Myy, Myz, Mzz [Nm].
   M = [-0.7787, -0.1706, 1.4654, -4.2790, 4.3437, 5.0577]
   # Prior standard deviations of Mxx, Mxy, Mxz, Myy, Myz, Mzz [Nm].
   sigma_M = [5.0, 5.0, 5.0, 5.0, 5.0, 1.0]

   #==================================================================================
   # Origin time.
   #==================================================================================
   # Prior mean relative to event origin time [s].
   t = 0.0
   # Prior standard deviation [s].
   sigma_t = 4.0

   #==================================================================================
   # Source-time function coefficients.
   #==================================================================================
   # Prior means.
   s = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
   # Prior standard deviations.
   sigma_s = [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
