#=====================================================================================
# Inversion parameters.
#=====================================================================================

   #==================================================================================
   # Method.
   #==================================================================================
   # HMC (Hamiltonian Monte Carlo), MH (Metropolis-Hastings), LIN (linear system).
   method = "HMC_N"

   #==================================================================================
   # Number of model parameters.
   #==================================================================================
   # 6 (moment tensor, M), 9 (M plus location), 10 (M plus location plus time).
   dim = 6

   #==================================================================================
   # General Monte Carlo parameters.
   #==================================================================================
   # Number of samples.
   n_samples = 10000

   #==================================================================================
   # HMC-specific parameters.
   #==================================================================================
   # HMC trajectory time increment.
   hmc_dt = 0.1
   # HMC number of trajectory time steps.
   hmc_nt = 100
   # HMC integration length ("random", "fixed").
   hmc_length = "random"
   # HMC mass matrix regularisation (small: little regularisation, large: mass matrix=identity).
   hmc_reg = 0.01
   # Write Hamiltonian trajectory to ../output/trajectory.txt. ("yes" or "no")
   hmc_output_trajectory = "no"

   #==================================================================================
   # Output.
   #==================================================================================
   # Write basic screen output ("yes" or "no").
   verbose = "yes"

#=====================================================================================
# Source parameters.
#=====================================================================================

   #==================================================================================
   # Source location.
   #==================================================================================
   # Prior means of latitude [degree], longitude [degree], depth [km].
   lat = 141.0
   lon = 32.2
   depth = 51.0
   # Prior standard deviations of latitude [degree], longitude [degree], depth [km].
   sigma_lat = 1.0
   sigma_lon = 1.0
   sigma_depth = 1.0
   # Scaling factors multiplying the values given above (for better conditioning).
   scale_lat = 1.0
   scale_lon = 1.0
   scale_depth = 1000.0

   #==================================================================================
   # Moment tensor.
   #==================================================================================
   # Prior means of Mxx, Mxy, Mxz, Myy, Myz, Mzz [Nm].
   M = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
   # Prior standard deviations of Mxx, Mxy, Mxz, Myy, Myz, Mzz [Nm].
   sigma_M = [1000.1, 1000.1, 1000.1, 1000.1, 1000.1, 1000.1]
   # Scaling factors multiplying the values given above (for better conditioning).
   scale_M = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

   #==================================================================================
   # Origin time.
   #==================================================================================
   # Prior mean relative to event origin time [s].
   t = 0.0
   # Prior standard deviation [s].
   sigma_t = 0.1
   # Scaling factor multiplying the values given above (for better conditioning).
   scale_t = 0.1
